### ISSUE TITLE
prefetch_count value is ignored

### ISSUE THREAD

**Issue by shauryagarg2006** [logstash-plugins/logstash-input-azure_event_hubs#60]
The configuration option `prefetch_count` is not used anywhere and is ignored,

I think we need to set the value here:

https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/6b741f19d18ff63c5c0435555679ddd3832d64fe/lib/logstash/inputs/azure_event_hubs.rb#L411

**Comment by digitalbydesign** [comment]
I'm also having an issue trying to raise the default prefetch_count higher than 300 but having issues. I've read in different places to adjust the maxBatchSize to something like 1000 but the plugin errors out since that is higher than the prefetch_count (300). Any ideas how to properly set this higher than 300?
